steps:
  - id: 'terraform init'
    name: gcr.io/cloud-builders/terraform'
    script: terraform init
  - name: 'gcr.io/cloud-builders/terraform'
    entrypoint: 'bash'
    args:
      - '-c'
      - | 
        
        echo "Hello World"
        chmod +x targetd.sh
        echo 'terrafrom version'
        terraform init
        bash targetd.sh


options:
  logging: CLOUD_LOGGING_ONLY    
