steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
      
        echo "Hello World"
        chmod +x sqlstartstop.sh
        bash sqlstartstop.sh

options:
  logging: CLOUD_LOGGING_ONLY   