steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.0.0'
    script: terraform init
  - name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - | 
        
        echo "Hello World"
        chmod +x targetd.sh
        echo 'terrafrom version'
        terraform init
        sh targetd.sh


options:
  logging: CLOUD_LOGGING_ONLY    
