steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.1.9'
    script: terraform init
  - id: 'terraform destroy' 
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x targetd.sh
        sh targetd.sh 
options:
  logging: CLOUD_LOGGING_ONLY    
