steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.0.0'
    script: terraform init
  
  - id: 'terraform destroy'
    name: 'hashicorp/terraform:1.0.0'
    script: terraform destroy --auto-approve 
options:
  logging: CLOUD_LOGGING_ONLY    
