steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.1.9'
    script: terraform init
  - name: 'bash'
    script: |
      #!/usr/bin/env bash
      echo "Hello World"
      chmod +x targetd.sh
      sh targetd.sh 
options:
  logging: CLOUD_LOGGING_ONLY    
