steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.1.9'
    script: terraform init
  - name: 'hashicorp/terraform:1.1.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - | 
        
        echo "Hello World"
        chmod +x targetd.sh
        bash targetd.sh

options:
  logging: CLOUD_LOGGING_ONLY    
